# -*- coding: utf-8 -*-
"""losscomponent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WTxU20NvNsYNGFfKeutYkxUY1Y-kpWwk
"""

# -*- coding: utf-8 -*-
import streamlit as st
import pandas as pd
import numpy as np
from io import BytesIO
from datetime import date

st.set_page_config(page_title="Loss Component Calculator", layout="wide")

# ---------- CUSTOM CSS (African Actuarial Consultants theme) ----------
st.markdown("""
<style>
    /* Global */
    .stApp {
        background-color: #FFFFFF;
        color: #000000;
        font-family: 'Calisto MT', serif;
        font-size: 11pt;
    }
    /* Header / Navigation */
    .header {
        background-color: #000000;
        padding: 1rem 2rem;
        display: flex;
        align-items: center;
        justify-content: flex-end;
        border-bottom: 3px solid #D4AF37;
    }
    .nav-links a {
        color: #FFFFFF;
        margin-left: 2rem;
        text-decoration: none;
        font-weight: 500;
        transition: color 0.3s;
    }
    .nav-links a:hover {
        color: #D4AF37;
    }
    /* Hero Section */
    .hero {
        background: linear-gradient(135deg, #000000 0%, #333333 100%);
        color: #FFFFFF;
        padding: 2rem 2rem;
        text-align: center;
        border-bottom: 3px solid #D4AF37;
    }
    .hero h1 {
        color: #D4AF37;
        font-size: 2.5rem;
        margin-bottom: 0.5rem;
    }
    .hero p {
        font-size: 1.2rem;
        max-width: 800px;
        margin: 0 auto;
    }
    /* Main container */
    .main-container {
        max-width: 1400px;
        margin: 2rem auto;
        padding: 0 2rem;
    }
    /* Cards */
    .card {
        background-color: #F9F9F9;
        border: 1px solid #D4AF37;
        border-radius: 8px;
        padding: 1.5rem;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        margin-bottom: 2rem;
    }
    .card h3 {
        color: #D4AF37;
        margin-top: 0;
        border-bottom: 2px solid #D4AF37;
        padding-bottom: 0.5rem;
    }
    /* Footer */
    .footer {
        background-color: #000000;
        color: #FFFFFF;
        text-align: center;
        padding: 1.5rem;
        border-top: 3px solid #D4AF37;
        margin-top: 3rem;
    }
    .footer a {
        color: #D4AF37;
        text-decoration: none;
    }
    /* Streamlit element overrides */
    .stButton > button, .stDownloadButton > button {
        background-color: #D4AF37;
        color: #000000;
        border: none;
        border-radius: 4px;
        font-weight: bold;
        padding: 0.5rem 1rem;
        transition: all 0.3s;
    }
    .stButton > button:hover, .stDownloadButton > button:hover {
        background-color: #B8960F;
        color: #FFFFFF;
    }
    .stFileUploader {
        border: 2px dashed #D4AF37;
        border-radius: 5px;
        padding: 1rem;
    }
    .dataframe {
        border: 1px solid #D4AF37;
        border-radius: 8px;
        overflow: hidden;
    }
</style>
""", unsafe_allow_html=True)

# ---------- Header ----------
st.markdown("""
<div class="header">
    <div class="nav-links">
        <a href="#">Home</a>
        <a href="#">Services</a>
        <a href="#">Tools</a>
        <a href="#">Contact</a>
    </div>
</div>
""", unsafe_allow_html=True)

# ---------- Hero ----------
st.markdown("""
<div class="hero">
    <h1>Loss Component Calculator</h1>
    <p>Upload your Excel file with the required columns. The app calculates Loss Ratio, Commission Ratio, Expense Ratio, Risk Adjustment Ratio, Combined Ratio, and the Loss Component.</p>
</div>
""", unsafe_allow_html=True)

# ---------- Main Container ----------
st.markdown('<div class="main-container">', unsafe_allow_html=True)

# --- User inputs ---
col1, col2 = st.columns(2)
with col1:
    client_name = st.text_input("Client Name (for file name)", value="Client").strip()
with col2:
    # empty for spacing
    pass

# File uploader
uploaded_file = st.file_uploader("Choose an Excel file", type=["xlsx", "xls"])

if uploaded_file is not None:
    try:
        # Read Excel file
        df = pd.read_excel(uploaded_file)

        # Drop unnamed columns
        unnamed = [c for c in df.columns if c.startswith('Unnamed:')]
        if unnamed:
            df = df.drop(columns=unnamed)
            st.info(f"Dropped {len(unnamed)} unnamed column(s).")

        # Preview
        with st.expander("Preview of uploaded data"):
            st.dataframe(df.head())

        # Required columns
        required_cols = [
            'Line_of_business',
            'Gross_Written_Premiums',
            'Gross_Attributable_Expenses',
            'Gross_Commission_Paid',
            'Gross_Paid_Claims',
            'Gross_Opening_OCR',
            'Gross_Closing_OCR',
            'Gross_Opening_IBNR',
            'Gross_Closing_IBNR',
            'Gross_Opening_UPR',
            'Gross_Closing_UPR'
        ]

        missing = [col for col in required_cols if col not in df.columns]
        if missing:
            st.error(f"Missing required columns: {', '.join(missing)}. Please ensure your Excel file contains all required columns.")
        else:
            # --- Perform calculations ---

            # 1. Gross Actual Incurred Claims
            df["Gross_Actual_Incurred_Claims"] = (
                df["Gross_Paid_Claims"] +
                df["Gross_Closing_IBNR"] +
                df["Gross_Closing_OCR"] -
                df["Gross_Opening_IBNR"] -
                df["Gross_Opening_OCR"]
            )

            # 2. Gross Earned Premiums
            df["Gross_Earned_Premiums"] = (
                df["Gross_Written_Premiums"] +
                df["Gross_Opening_UPR"] -
                df["Gross_Closing_UPR"]
            )

            # 3. Loss Ratio (avoid division by zero)
            df["Loss_Ratio"] = np.where(
                df["Gross_Earned_Premiums"] != 0,
                df["Gross_Actual_Incurred_Claims"] / df["Gross_Earned_Premiums"],
                np.nan
            )

            # 4. Commission Ratio
            df["Commission_Ratio"] = np.where(
                df["Gross_Written_Premiums"] != 0,
                df["Gross_Commission_Paid"] / df["Gross_Written_Premiums"],
                np.nan
            )

            # 5. Expense Ratio
            df["Expense_Ratio"] = np.where(
                df["Gross_Written_Premiums"] != 0,
                df["Gross_Attributable_Expenses"] / df["Gross_Written_Premiums"],
                np.nan
            )

            # 6. Risk Adjustment Ratio (sum of closing IBNR and OCR)
            risk_adjustment_denom = df["Gross_Closing_IBNR"] + df["Gross_Closing_OCR"]
            df["Risk_Adjustment_Ratio"] = np.where(
                risk_adjustment_denom != 0,
                df["Gross_Risk_Adjustment"] / risk_adjustment_denom,
                np.nan
            )

            # 7. Combined Ratio
            df["Combined_Ratio"] = (
                df["Loss_Ratio"] +
                df["Commission_Ratio"] +
                df["Expense_Ratio"] +
                df["Risk_Adjustment_Ratio"]
            )

            # 8. Loss Component (excess above 100%)
            df["Loss_Component"] = np.maximum(df["Combined_Ratio"] - 1, 0) * df["Gross_Closing_UPR"]

            # --- Aggregate results by Line of Business ---
            result = df.groupby('Line_of_business').agg({
                'Gross_Written_Premiums': 'sum',
                'Gross_Earned_Premiums': 'sum',
                'Gross_Actual_Incurred_Claims': 'sum',
                'Loss_Ratio': 'mean',
                'Commission_Ratio': 'mean',
                'Expense_Ratio': 'mean',
                'Risk_Adjustment_Ratio': 'mean',
                'Combined_Ratio': 'mean',
                'Loss_Component': 'sum'
            }).reset_index()

            # Rename columns for clarity
            result = result.rename(columns={
                'Gross_Written_Premiums': 'Total_Written_Premiums',
                'Gross_Earned_Premiums': 'Total_Earned_Premiums',
                'Gross_Actual_Incurred_Claims': 'Total_Incurred_Claims'
            })

            # Display results
            st.markdown('<div class="card">', unsafe_allow_html=True)
            st.subheader("Loss Component Results by Line of Business")

            # Format numeric columns for display
            display_result = result.copy()
            for col in display_result.columns:
                if col != 'Line_of_business':
                    if 'Ratio' in col:
                        display_result[col] = display_result[col].apply(lambda x: f"{x:.2%}" if pd.notna(x) else "N/A")
                    else:
                        display_result[col] = display_result[col].apply(lambda x: f"{x:,.2f}" if pd.notna(x) else "N/A")

            st.dataframe(display_result, use_container_width=True)
            st.markdown('</div>', unsafe_allow_html=True)

            # Prepare Excel download (raw numbers, not formatted)
            output = BytesIO()
            with pd.ExcelWriter(output, engine='openpyxl') as writer:
                result.to_excel(writer, index=False, sheet_name='Loss_Component_Results')
            output.seek(0)

            # Filename with client name
            safe_client = "".join(c for c in client_name if c.isalnum() or c in (' ', '-', '_')).rstrip()
            file_name = f"{safe_client}_Loss_Component_Results.xlsx" if safe_client else "Loss_Component_Results.xlsx"

            st.download_button(
                label="Download results as Excel",
                data=output,
                file_name=file_name,
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )

            # Optional: Show raw data with all calculations
            with st.expander("View Detailed Calculations (all rows)"):
                # Format for display
                detail_display = df.copy()
                for col in detail_display.columns:
                    if 'Ratio' in col and col not in required_cols:
                        detail_display[col] = detail_display[col].apply(lambda x: f"{x:.2%}" if pd.notna(x) else "N/A")
                    elif col not in required_cols and col not in ['Line_of_business']:
                        detail_display[col] = detail_display[col].apply(lambda x: f"{x:,.2f}" if pd.notna(x) else "N/A")
                st.dataframe(detail_display, use_container_width=True)

    except Exception as e:
        st.error(f"An error occurred: {e}")
        st.write("Please check your Excel file format and column names.")

st.markdown('</div>', unsafe_allow_html=True)  # close main-container

# ---------- Footer ----------
st.markdown("""
<div class="footer">
    <p>© 2026 African Actuarial Consultants. All rights reserved. | <a href="#">Privacy</a> | <a href="#">Terms</a></p>
    <p style="margin-top: 0.5rem; font-size: 0.9rem;">Powered by Vanababa</p>
</div>
""", unsafe_allow_html=True)